---
- name: Check pending reboot
  ansible.windows.win_shell: |
    $rebootPending = Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending"

    if ($rebootPending) {
      Write-Output "YES"
    }
    else {
      Write-Output "NO"
    }
  register: reboot_status

- debug:
    msg: "Pending Reboot: {{ reboot_status.stdout }}"
