---
- name: Enterprise Windows Patching
  hosts: windows
  gather_facts: yes

  tasks:

    - include_tasks: check_reboot.yml

    - name: Scan Available Updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      register: scan_result

    - name: Display Available Updates
      debug:
        msg: "Updates Found: {{ scan_result.found_update_count }}"

    - name: Install Security Updates and Critical Updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
      register: update_result

    - include_tasks: validate.yml
