---
# Verify installed KBs

- name: Get installed hotfixes
  ansible.windows.win_shell: |
    Get-HotFix | Select-Object HotFixID
  register: installed_kbs

- name: Display installed KBs
  debug:
    var: installed_kbs.stdout_lines

# Verify reboot status

- name: Verify reboot status
  ansible.windows.win_shell: |
    $rebootPending = Test-Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending"

    if ($rebootPending) {
      Write-Output "REBOOT_REQUIRED"
    }
    else {
      Write-Output "HEALTHY"
    }
  register: reboot_check

- name: Connectivity validation
  ansible.windows.win_ping

# Deployment Summary

- name: Deployment Summary
  debug:
    msg:
      - "Host: {{ inventory_hostname }}"
      - "Updates Found: {{ scan_result.found_update_count | default(0) }}"
      - "Updates Installed: {{ update_result.installed_update_count | default(0) }}"
      - "Reboot Required: {{ update_result.reboot_required | default(false) }}"
      - "System Status: {{ reboot_check.stdout }}"
